SELECT * FROM ZONE WHERE ZONE_ID = '1';



CREATE SEQUENCE SEQ_SPECIES
 START WITH 13
 NOCACHE;

SELECT * FROM species;


SELECT * FROM restaurant;

SELECT * FROM KEEPER;

CREATE SEQUENCE SEQ_KEEPERALTER
	START WITH 10
	NOCACHE;

-- 회원 / 게시판
-- 회원파트 : C(회원가입) / R(로그인) / 로그아웃
-- 게시글 작성 조건 : 로그인 5회 이상
-- 게시판 : C(게시글 작성) / R(목록조회) / R(상세조회)

CREATE TABLE JDBC_MEMBER(
	MEMBER_ID VARCHAR2(30) PRIMARY KEY,
	MEMBER_PWD VARCHAR2(30) NOT NULL,
	MEMBER_NAME VARCHAR2(30) NOT NULL
);
CREATE TABLE JDBC_BOARD(
	BOARD_NO NUMBER GENERATED ALWAYS AS IDENTITY,
	BOARD_TITLE NVARCHAR2(2000) NOT NULL,
	BORAD_CONTENT NVARCHAR2(2000) NOT NULL,
	BOARCH_WRITER VARCHAR2(30) NOT NULL,
	FOREIGN KEY(BOARCH_WRITER) REFERENCES JDBC_MEMBER(MEMBER_ID)
);

CREATE TABLE LOGIN_CHECK(
	LOGIN_ID NUMBER GENERATED ALWAYS AS IDENTITY,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	LOGIN_DATE DATE DEFAULT SYSDATE,
	FOREIGN KEY(MEMBER_ID) REFERENCES JDBC_MEMBER
);


SELECT * FROM JDBC_MEMBER;

