-- 회원번호 --1,2,3,... 들어갈 값이 어떤 값인가??
-- 아이디 -- user01, user01,...
-- 비밀번호 -- pass01, pass02,...
-- 이름	-- 홍길동, 고길동, ...
-- 이메일	-- kh@kh.com, kh@naver.com, ...
-- 가입일	-- SYSDATE
-- 회원정보수정일 -SYSDATE
-- 삭제여부	-'Y' / 'N'

CREATE TABLE WEB_MEMBER(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(30) UNIQUE NOT NULL,
	USER_PWD VARCHAR2(30) NOT NULL,
	USER_NAME NVARCHAR2(20) NOT NULL,
	EMAIL VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE,
	MODIFY_DATE DATE DEFAULT SYSDATE,
	STATUS CHAR(1) DEFAULT 'N' CHECK(STATUS IN ('Y','N'))
);
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;
SELECT * FROM WEB_MEMBER;
INSERT INTO WEB_MEMBER
	VALUES (SEQ_MEMBER_NO.NEXTVAL,
			'admin',
			'1234',
			'관리자',
			'admin@kh.com',
			SYSDATE,
			SYSDATE,
			'N');
---------------------------------------------------------
CREATE TABLE WEB_BOARD(
	BOARD_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	USER_NO NUMBER REFERENCES WEB_MEMBER,
	BOARD_TITLE NVARCHAR2(50) NOT NULL,
	BOARD_CONTENT NVARCHAR2(2000) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	MODIFY_DATE DATE DEFAULT SYSDATE,
	COUNT NUMBER DEFAULT 0,
	STATUS CHAR(1) DEFAULT 'N' CHECK(STATUS IN ('Y','N'))
);

INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(1, '오늘 뭐 먹을까.', '안녕하세요~ 반갑습니다.');
INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(2, '김치볶음밥 어떻세요', '안녕하세요~ 반갑습니다.');
INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(3, '오므라이스도 좋은데.', '안녕하세요~ 반갑습니다.');

SELECT * FROM WEB_mEMBER;
SELECT * FROM WEB_BOARD;

COMMIT;

SELECT BOARD_NO, BOARD_TITLE, RNUM
FROM 
(SELECT
		BOARD_NO, BOARD_TITLE, ROWNUM RNUM
	FROM (SELECT
				BOARD_NO,
				BOARD_TITLE,
				ROWNUM
			FROM
				WEB_BOARD;
			ORDER
			   BY
				CREATE_DATE DESC))
	WHERE
		RNUM BETWEEN 4 AND 6;


SELECT 
		BOARD_NO,
		BOARD_TITLE
	FROM
		WEB_BOARD
	ORDER
		BY
		CREATE_DATE DESC
	OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY;

CREATE TABLE WEB_ATTACHMENT(
	FILE_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
	REF_BNO NUMBER NOT NULL,
	ORIGIN_NAME VARCHAR2(100) NOT NULL,
	CHANG_NAME VARCHAR2(50) NOT NULL,
	FILE_PATH VARCHAR2(100) NOT NULL,
	BOARD_TYPE CHAR(1) NO NULL,
	FILE_LEVEL NUMBER NOT NULL,
	CREATE_DATE DEFAULT SYSDATE
	
	
);



