DROP TABLE ROOM;

CREATE TABLE ROOM (
	ROOM_NUMBER	CHAR(5)		NOT NULL,
	ROOM_RANK	VARCHAR2(9)		NOT NULL,
	EMPTY	CHAR(1),
	PRICE	NUMBER		NOT NULL,
	
	CONSTRAINT EMP_CK CHECK (EMPTY IN ('Y', 'N'))
);

DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER (
	CUSTOMER_ID	CHAR(20)		NOT NULL,
	CUSTOMER_RANK	CHAR(1)	DEFAULT 'C',
	PHONE_NUMBER	CHAR(20)		NOT NULL,
	CUSTOMER_NAME	VARCHAR2(20)		NOT NULL,
	
	CONSTRAINT CRN_CK CHECK (CUSTOMER_RANK IN ('A','B','C'))
);






